### ISSUE TITLE
fastq-dump corrupting fastq files during compression

### ISSUE THREAD

**Issue by ClaireMGreen** [ncbi/sra-tools#118]
I am using sra-toolkit.2.8.2-1-centos_linux64 on the University of Sheffield (UK) HPC Sharc to convert 73 sra files into gzipped fastq files. 

If I run:

```
#!/bin/bash
#$ -l rmem=8G -l mem=8G
#$ -pe openmp 8
#$ -j y
#$ -l h_rt=48:00:00
#$ -m bea
#$ -P rse

../../sratoolkit.2.8.2-1-centos_linux64/bin/fastq-dump.2.8.2 --gzip SRR2015713.sra SRR2015714.sra SRR2015715.sra SRR2015716.sra
```

then the fastq.gz files are created with no errors. However if I try and run these files through the [bcbio](http://bcbio-nextgen.readthedocs.io/en/latest/contents/introduction.html) pipeline I get this error:

```
[2018-03-09T20:42Z] Running STAR aligner on /shared/hidelab2/user/mdp15cmg/TDP-43/DUM_RNASEQ/sra/SRR2015731.fastq.gz and /usr/local/community/bcbio-nextgen/2017-08/data/genomes/Hsapiens/GRCh37/star/
[2018-03-09T20:59Z] gzip: /shared/hidelab2/user/mdp15cmg/TDP-43/DUM_RNASEQ/sra/SRR2015731.fastq.gz: unexpected end of file
[2018-03-09T20:59Z] EXITING because of FATAL ERROR in reads input: quality string length is not equal to sequence length
[2018-03-09T20:59Z] @SRR2015731.31714928
[2018-03-09T20:59Z] AAGGCCGAGGGGGCTGTGTGTGACCCTGGTAGGAGCAAACCGAGTGC
[2018-03-09T20:59Z] ACCCTTTGTACTGTCAACTCTGGCCATGTTTCCAGGAGGGGCCATGGGGGTCAGGGTGGTTTTGAGAGAGCAGGGTAAGGAAGGAATGTGCTAGAAGTGCTCCTAGTTTCTTGTAAAGGAAGCC
[2018-03-09T20:59Z] SOLUTION: fix your fastq file
[2018-03-09T20:59Z] Mar 09 20:59:46 ...... FATAL ERROR, exiting
[2018-03-09T20:59Z] [W::bgzf_read_block] EOF marker is absent. The input is probably truncated
[2018-03-09T20:59Z] samtools sort: truncated file. Aborting
[2018-03-09T20:59Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/usr/local/extras/bcbio-nextgen/2017-08/data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /usr/local/community/bcbio-nextgen/2017-08/data/galaxy/../anaconda/bin/STAR --genomeDir /usr/local/community/bcbio-nextgen/2017-08/data/genomes/Hsapiens/GRCh37/star/ --readFilesIn /shared/hidelab2/user/mdp15cmg/TDP-43/DUM_RNA$
gzip: /shared/hidelab2/user/mdp15cmg/TDP-43/DUM_RNASEQ/sra/SRR2015731.fastq.gz: unexpected end of file
EXITING because of FATAL ERROR in reads input: quality string length is not equal to sequence length
@SRR2015731.31714928
AAGGCCGAGGGGGCTGTGTGTGACCCTGGTAGGAGCAAACCGAGTGC
ACCCTTTGTACTGTCAACTCTGGCCATGTTTCCAGGAGGGGCCATGGGGGTCAGGGTGGTTTTGAGAGAGCAGGGTAAGGAAGGAATGTGCTAGAAGTGCTCCTAGTTTCTTGTAAAGGAAGCC
SOLUTION: fix your fastq file
Mar 09 20:59:46 ...... FATAL ERROR, exiting
[W::bgzf_read_block] EOF marker is absent. The input is probably truncated
samtools sort: truncated file. Aborting
' returned non-zero exit status 1
hello
```
Similarly, if I run ``` zcat SRRthing.fastq.gz | wc ``` to get the word could I get the same error: "unexpected end of file"

When I went back to investigate, I realised the sra files themselves aren't corrupted, and if I run fastq dump WITHOUT the --gzip option, and then run gzip myself, it works fine. 

I have used both fastq-dump and fastq-dump.2.8.2. Interestingly, the latter worked fine for one batch, but corrupted the other two batches (I have checked for errors, and can confirm the submission files were identical). In summary, I believe there is a bug in the gzip process included within fastq-dump.

**Comment by gexijin** [comment]
I got the same error.
